#!/usr/bin/env python3
"""
optimize_topics.py
Extracts shared CSS/JS from topic HTML files to reduce duplication.
  Type A (topics 01-14): complex quiz design, different accent colors
  Type B (topics 15-28): tab navigation, mixed accent colors
"""

import re
from pathlib import Path

TOPICS_DIR = Path(r"C:\Users\Administrator\Documents\Claude\Projects\платформа для подготовки к блоковому экзамену\app\public\lessons\topics")

def read(p):
    return p.read_text(encoding="utf-8")

def write(p, content):
    p.write_text(content, encoding="utf-8", newline="\n")
    print(f"  wrote {p.name} ({len(content)//1024}KB)")


# ─── CSS helpers ──────────────────────────────────────────────

def extract_style_block(content):
    """Return (before, css_inner, after) splitting on <style>…</style>."""
    m = re.search(r"(<style>)(.*?)(</style>)", content, re.DOTALL)
    if not m:
        return None, None, None
    return content[: m.start()], m.group(2), content[m.end() :]


def extract_root_block(css):
    """Pull :root { … } from css; return (root_str, remaining_css)."""
    start = css.find(":root")
    if start == -1:
        return "", css
    brace = css.find("{", start)
    depth, pos = 0, brace
    while pos < len(css):
        if css[pos] == "{":
            depth += 1
        elif css[pos] == "}":
            depth -= 1
            if depth == 0:
                root = css[start : pos + 1]
                rest = css[:start] + css[pos + 1 :]
                return root.strip(), rest
        pos += 1
    return "", css


# ─── TYPE A: topics 01-14 ────────────────────────────────────

def build_shared_a_css():
    """Build topic-shared-a.css from topic-01 (largest, most complete CSS)."""
    content = read(TOPICS_DIR / "topic-01.html")
    _, css, _ = extract_style_block(content)
    if css is None:
        raise RuntimeError("No <style> in topic-01.html")

    _, shared = extract_root_block(css)
    shared = shared.strip()

    # Ensure KaTeX helpers are present (some topics add them, some don't)
    if ".katex {" not in shared and ".katex{" not in shared:
        shared += (
            "\n      .katex { font-size: 1.05em !important; }"
            "\n      .katex-display { overflow-x: auto; padding: 6px 0; }"
        )

    out = f"/* topic-shared-a.css — common styles for Type A topics (01–14)\n"
    out += f"   Generated by optimize_topics.py — do not edit manually */\n\n"
    out += shared + "\n"
    write(TOPICS_DIR / "topic-shared-a.css", out)
    return out


def update_type_a_css(fname, shared_css_lines):
    filepath = TOPICS_DIR / fname
    content = read(filepath)
    before, css, after = extract_style_block(content)
    if css is None:
        print(f"  SKIP {fname}: no <style> found")
        return 0

    root, _ = extract_root_block(css)
    old_lines = css.count("\n")

    # Re-insert only the :root block + link to shared CSS
    link = '    <link rel="stylesheet" href="topic-shared-a.css" />'
    new_style = f"    <style>\n      {root}\n    </style>\n{link}"
    new_content = before + new_style + after
    write(filepath, new_content)
    saved = old_lines - root.count("\n")
    print(f"    saved ~{saved} CSS lines")
    return saved


def process_type_a():
    print("\n=== TYPE A: topics 01-14 (CSS extraction) ===")
    css_out = build_shared_a_css()
    shared_lines = css_out.count("\n")

    total_saved = 0
    for i in range(1, 15):
        fname = f"topic-{i:02d}.html"
        print(f"  {fname}")
        total_saved += update_type_a_css(fname, shared_lines)

    print(f"\n  Total CSS lines saved (Type A): ~{total_saved}")


# ─── TYPE B: topics 15-28 ────────────────────────────────────

# Accent color overrides for topics that differ from the orange base
TYPE_B_ACCENT_OVERRIDES = {
    "topic-15.html": ("#0ea5e9", "rgba(14,165,233,0.18)"),   # blue
    "topic-16.html": ("#6366f1", "rgba(99,102,241,0.18)"),   # indigo
}

# Common :root for Type B orange topics (17-28)
TYPE_B_ROOT_ORANGE = """:root {
  --accent: #f97316;
  --accent-dark: #ea6c0a;
  --bg: #0f172a;
  --bg-card: #1e293b;
  --text: #f1f5f9;
  --text-muted: #94a3b8;
  --border: rgba(148, 163, 184, 0.15);
  --success: #22c55e;
  --warning: #f59e0b;
  --error: #ef4444;
  --radius: 14px;
}"""


def build_shared_b_css():
    """
    Build topic-shared-b.css from topic-25 (smallest Type B = pure shared base).
    The :root uses the common orange palette.
    """
    content = read(TOPICS_DIR / "topic-25.html")
    _, css, _ = extract_style_block(content)
    if css is None:
        raise RuntimeError("No <style> in topic-25.html")

    # topic-25 already has the orange :root; strip it and replace with canonical
    _, body = extract_root_block(css)

    out = "/* topic-shared-b.css — common styles for Type B topics (15–28)\n"
    out += "   Generated by optimize_topics.py — do not edit manually */\n\n"
    out += TYPE_B_ROOT_ORANGE + "\n\n"
    out += "html { scroll-behavior: smooth; }\n"
    out += body.strip() + "\n"
    write(TOPICS_DIR / "topic-shared-b.css", out)
    return out


def update_type_b_css(fname):
    filepath = TOPICS_DIR / fname
    content = read(filepath)
    before, css, after = extract_style_block(content)
    if css is None:
        print(f"  SKIP {fname}: no <style> found")
        return 0

    old_lines = css.count("\n")

    # Determine accent override if needed
    override = TYPE_B_ACCENT_OVERRIDES.get(fname)

    if override:
        accent_color, accent_dim = override
        inline_root = f"""    <style>
      :root {{
        --accent: {accent_color};
        --accent-dim: {accent_dim};
      }}
    </style>"""
        link = '    <link rel="stylesheet" href="topic-shared-b.css" />'
        new_block = inline_root + "\n" + link
    else:
        # Orange topics: just link, no inline style
        new_block = '    <link rel="stylesheet" href="topic-shared-b.css" />'

    # Find any EXTRA css not in the base (selectors beyond topic-25's base)
    # Strategy: topic-25 has 96 lines; anything extra stays inline
    # We normalise whitespace to find the common block boundary.
    # Simple heuristic: keep CSS after a "─── extra ───" style comment or
    # after the base block ends. For safety, we keep ALL non-base css inline.

    # Split: find where topic-specific CSS starts by looking for selectors
    # that don't exist in topic-25 base.
    base_content = read(TOPICS_DIR / "topic-shared-b.css")
    base_selectors = set(re.findall(r"([.#\w][\w-]*(?:\s*[>+~]\s*[.#\w][\w-]*)*)(?=\s*\{)", base_content))

    # Collect all CSS rules from this file's style block
    all_rules = re.findall(r"([^{}]+)\{([^{}]*)\}", css, re.DOTALL)
    extra_rules = []
    for selector, body_css in all_rules:
        sel = selector.strip()
        # Rough check: if any token in selector isn't in base, it's extra
        tokens = re.findall(r"[.#]?[\w-]+", sel)
        is_base = any(
            sel.strip().replace("\n", "").replace("  ", " ") in bs
            for bs in base_selectors
        )
        if not is_base and sel.strip() not in (":root", "html", "body",
                                                "*", "*::before", "*::after"):
            extra_rules.append(f"    {sel.strip()} {{\n      {body_css.strip()}\n    }}")

    if extra_rules:
        extra_block = "\n    <style>\n" + "\n".join(extra_rules) + "\n    </style>"
        new_block = new_block + extra_block

    new_content = before + "\n" + new_block + after
    write(filepath, new_content)
    saved = old_lines - (new_block.count("\n"))
    print(f"    saved ~{max(0,saved)} CSS lines")
    return max(0, saved)


def process_type_b():
    print("\n=== TYPE B: topics 15-28 (CSS extraction) ===")
    build_shared_b_css()
    total_saved = 0
    for i in range(15, 29):
        fname = f"topic-{i:02d}.html"
        print(f"  {fname}")
        total_saved += update_type_b_css(fname)
    print(f"\n  Total CSS lines saved (Type B): ~{total_saved}")


# ─── TYPE A JS: extract quiz engine ──────────────────────────

QUIZ_ENGINE_MARKER = "let dIdx = 0"  # start of shared quiz state+functions

def build_shared_a_js():
    """Extract quiz engine from topic-01 → topic-shared-a.js."""
    content = read(TOPICS_DIR / "topic-01.html")

    # Find the <script> block at end of body
    m = re.search(r"<script>\s*([\s\S]+?)\s*</script>\s*</body>", content)
    if not m:
        raise RuntimeError("No script block found in topic-01.html")
    script = m.group(1)

    # Find quiz engine start
    idx = script.find(QUIZ_ENGINE_MARKER)
    if idx == -1:
        raise RuntimeError(f"Marker '{QUIZ_ENGINE_MARKER}' not found")

    # Also grab the K config if it appears before the quiz marker
    # (some topics define K before slides, others after)
    k_idx = script.rfind("const K = {")
    if k_idx != -1 and k_idx < idx:
        # K is defined before quiz engine – we'll include it from the pre-idx section
        quiz_engine = script[k_idx:].strip()
    else:
        quiz_engine = script[idx:].strip()

    out = "/* topic-shared-a.js — quiz engine for Type A topics (01-14)\n"
    out += "   Requires: QS array defined before this script loads.\n"
    out += "   Generated by optimize_topics.py */\n\n"
    out += quiz_engine + "\n"
    write(TOPICS_DIR / "topic-shared-a.js", out)
    return quiz_engine


def update_type_a_js(fname):
    """Remove quiz engine from inline script; add <script src> tag."""
    filepath = TOPICS_DIR / fname
    content = read(filepath)

    # Find script block at end of body
    m = re.search(r"(<script>)([\s\S]+?)(</script>)\s*(</body>)", content)
    if not m:
        print(f"  SKIP {fname}: no script block found")
        return 0

    script_inner = m.group(2)
    old_lines = script_inner.count("\n")

    # Find quiz engine start (try multiple spellings)
    for marker in ["      let dIdx = 0", "      let dIdx=0", "let dIdx = 0,"]:
        idx = script_inner.find(marker)
        if idx != -1:
            break

    if idx == -1:
        print(f"  SKIP {fname}: quiz marker not found")
        return 0

    # Also handle K config appearing before quiz (move it after QS in split)
    k_idx = script_inner.rfind("      const K = {")
    if k_idx != -1 and k_idx < idx:
        # Remove K block from inline (it'll be in shared JS)
        # Find end of K block
        k_end = script_inner.find("};", k_idx)
        if k_end != -1:
            k_end += 2  # include "};"
            k_end2 = script_inner.find("\n", k_end) + 1
            # Also remove renderMathNow right after K if present
            rm_start = script_inner.find("      function renderMathNow(", k_end2)
            if rm_start != -1:
                rm_end = script_inner.find("\n      }", rm_start) + len("\n      }")
                script_inner = script_inner[:k_idx] + script_inner[rm_end:]
                idx = script_inner.find("      let dIdx = 0")
                if idx == -1:
                    idx = script_inner.find("let dIdx = 0,")
            else:
                script_inner = script_inner[:k_idx] + script_inner[k_end2:]
                idx = script_inner.find("      let dIdx = 0")
                if idx == -1:
                    idx = script_inner.find("let dIdx = 0,")

    if idx == -1:
        print(f"  SKIP {fname}: quiz marker lost after K removal")
        return 0

    # Keep only the pre-quiz portion in inline script
    inline_part = script_inner[:idx].rstrip()
    new_lines = inline_part.count("\n")

    new_script_section = (
        f"    <script>\n{inline_part}\n    </script>\n"
        f'    <script src="topic-shared-a.js"></script>'
    )

    new_content = (
        content[: m.start()]
        + new_script_section
        + "\n  </body>"
    )
    write(filepath, new_content)
    saved = old_lines - new_lines
    print(f"    saved ~{saved} JS lines")
    return saved


def process_type_a_js():
    print("\n=== TYPE A: topics 01-14 (JS extraction — quiz engine) ===")
    build_shared_a_js()
    total_saved = 0
    for i in range(1, 15):
        fname = f"topic-{i:02d}.html"
        print(f"  {fname}")
        total_saved += update_type_a_js(fname)
    print(f"\n  Total JS lines saved (Type A): ~{total_saved}")


# ─── MAIN ────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys, io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    print("=== Topic Optimization Script ===")
    print(f"Working directory: {str(TOPICS_DIR).encode('ascii','replace').decode()}\n")

    process_type_a()
    process_type_b()
    process_type_a_js()

    print("\n=== Done! ===")
    print("Next steps:")
    print("  1. Test a Type A topic in browser (topic-01.html)")
    print("  2. Test a Type B topic in browser (topic-25.html)")
    print("  3. git add . && git commit")
